version: '3'

networks:
  ros:
    driver: bridge


services:
  master:
    image: osrf/ros:noetic-desktop-full
    container_name: master
    command: roscore
    networks:
      - ros
    restart: always
  mmdetection3d:
    image: mmdetection3d:latest
    build:
      context: ./mmdetection3d
      dockerfile: ./docker/Dockerfile
  mmdetection3d-ros:
    image: mmdetection3d-ros:latest
    build: .
    container_name: mmdetection3d-ros
    environment:
      - "DISPLAY=${DISPLAY}"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "ROS_HOSTNAME=rosnoetic"
      - "ROS_MASTER_URI=http://master:11311"
    volumes:
      - ./data:/data
      - ./models:/models
      - ./nodes:/nodes
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - ./mmdetection3d:/mmdetection3d
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    networks:
      - ros
    depends_on:
      - mmdetection3d